python_path: C:/Users/DELL/AppData/Local/Programs/Python/Python310/python.exe
script_path: F:/codes_crop_yield_prediction_updated/groundnut_GP_tehsil_pureml/source_code/main.py
working_directory: F:/codes_crop_yield_prediction_updated/groundnut_GP_tehsil_pureml/source_code
category: GP
load_models_path: F:/codes_crop_yield_prediction_updated/groundnut_GP_tehsil_pureml/models_15d/
num_districts: 28
pred_time: 15_days
run_mstac: false
scale_data: true
test: true
test_data_path: F:/codes_crop_yield_prediction_updated/groundnut_GP_tehsil_pureml/data/15d/test_data_15d_groundnut.csv
test_pred_path: F:/codes_crop_yield_prediction_updated/groundnut_GP_tehsil_pureml/data/15d/test_15d_groundnut_pred_GP.csv
test_yield_data_path: F:/codes_crop_yield_prediction_updated/groundnut_GP_tehsil_pureml/data/15d/true_test_yield_GP.csv
train: false
train_file_path: F:/codes_crop_yield_prediction_updated/groundnut_GP_tehsil_pureml/data/15d/train_data_15d_groundnut.csv
train_years: 17
train_yield_path: F:/codes_crop_yield_prediction_updated/groundnut_GP_tehsil_pureml/data/15d/train_yield_groundnut.csv
Crop: Groundnut
load_models_path2: F:/codes_crop_yield_prediction_updated/groundnut_GP_tehsil_pureml/models_15d/
