python_path: C:/Users/DELL/AppData/Local/Programs/Python/Python310/python.exe
script_path: F:\codes_crop_yield_prediction_updated\soybean_GP_tehsil_pureml\source_code\main.py
working_directory: F:\codes_crop_yield_prediction_updated\soybean_GP_tehsil_pureml\source_code
category: Tehsil
load_models_path: F:/codes_crop_yield_prediction_updated/soybean_GP_tehsil_pureml/data/1m/
num_districts: 28
pred_time: 1_month
run_mstac: true
scale_data: true
test: true
test_data_path:  F:/codes_crop_yield_prediction_updated/soybean_GP_tehsil_pureml/data/1m/test_data_1m_soybean.csv
test_pred_path: F:/codes_crop_yield_prediction_updated/soybean_GP_tehsil_pureml/data/1m/test_1m_soybean_pred_Tehsil.csv
test_yield_data_path: F:/codes_crop_yield_prediction_updated/soybean_GP_tehsil_pureml/data/1m/test_yield_soybean.csv
train: true
train_file_path: F:/codes_crop_yield_prediction_updated/soybean_GP_tehsil_pureml/data/1m/train_data_1m_soybean.csv
train_years: 17
train_yield_path: F:/codes_crop_yield_prediction_updated/soybean_GP_tehsil_pureml/data/1m/train_yield_soybean.csv
Crop: Soybean
